CREATE TABLE money_records (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES "Users" ON DELETE CASCADE,
  reference VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL,
  amount DOUBLE PRECISION NOT NULL
)