version: '3.8'

services:
  postgres_local:
    image: postgres
    container_name: postgres_local
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootpassword
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local