// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: money_records.sql

package db

import (
	"context"
)

const createMoneyRecord = `-- name: CreateMoneyRecord :one
INSERT INTO money_records (
  user_id, 
  reference,
  amount,
  status
) VALUES ($1, $2, $3, $4) RETURNING id, user_id, reference, status, amount
`

type CreateMoneyRecordParams struct {
	UserID    int32   `json:"user_id"`
	Reference string  `json:"reference"`
	Amount    float64 `json:"amount"`
	Status    string  `json:"status"`
}

func (q *Queries) CreateMoneyRecord(ctx context.Context, arg CreateMoneyRecordParams) (MoneyRecord, error) {
	row := q.db.QueryRowContext(ctx, createMoneyRecord,
		arg.UserID,
		arg.Reference,
		arg.Amount,
		arg.Status,
	)
	var i MoneyRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Reference,
		&i.Status,
		&i.Amount,
	)
	return i, err
}

const deleteMoneyRecordByID = `-- name: DeleteMoneyRecordByID :exec
DELETE FROM money_records WHERE reference = $1
`

func (q *Queries) DeleteMoneyRecordByID(ctx context.Context, reference string) error {
	_, err := q.db.ExecContext(ctx, deleteMoneyRecordByID, reference)
	return err
}

const getMoneyRecordByReference = `-- name: GetMoneyRecordByReference :one
SELECT id, user_id, reference, status, amount FROM money_records WHERE reference = $1
`

func (q *Queries) GetMoneyRecordByReference(ctx context.Context, reference string) (MoneyRecord, error) {
	row := q.db.QueryRowContext(ctx, getMoneyRecordByReference, reference)
	var i MoneyRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Reference,
		&i.Status,
		&i.Amount,
	)
	return i, err
}

const getMoneyRecordByStatus = `-- name: GetMoneyRecordByStatus :many
SELECT id, user_id, reference, status, amount FROM money_records WHERE status = $1
`

func (q *Queries) GetMoneyRecordByStatus(ctx context.Context, status string) ([]MoneyRecord, error) {
	rows, err := q.db.QueryContext(ctx, getMoneyRecordByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MoneyRecord{}
	for rows.Next() {
		var i MoneyRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Reference,
			&i.Status,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
